// <auto-generated />
namespace DataLayer.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FeaturesCorection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeaturesCorection));
        
        string IMigrationMetadata.Id
        {
            get { return "202004191558506_FeaturesCorection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
