// <auto-generated />
namespace DataLayer.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class useraddconfirmCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(useraddconfirmCode));
        
        string IMigrationMetadata.Id
        {
            get { return "202007270356163_user add confirmCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
