// <auto-generated />
namespace DataLayer.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddWeighToPackages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddWeighToPackages));
        
        string IMigrationMetadata.Id
        {
            get { return "202009151657375_AddWeighToPackages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
