// <auto-generated />
namespace DataLayer.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OrderStatuses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderStatuses));
        
        string IMigrationMetadata.Id
        {
            get { return "202004211823547_OrderStatuses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
