// <auto-generated />
namespace DataLayer.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Ad_OFFPercent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ad_OFFPercent));
        
        string IMigrationMetadata.Id
        {
            get { return "202008070933506_Ad_OFFPercent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
