// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Web.Areas.Admin.Controllers
{
    public partial class OrdersController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected OrdersController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult OrderAdrdressPrint()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OrderAdrdressPrint);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SetOrderFinlized()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetOrderFinlized);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public OrdersController Actions { get { return MVC.Admin.Orders; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Orders";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Orders";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string OpenOrders = "OpenOrders";
            public readonly string Index = "Index";
            public readonly string NotFinalizedOrders = "NotFinalizedOrders";
            public readonly string FinalizedOrders = "FinalizedOrders";
            public readonly string OrderAdrdressPrint = "OrderAdrdressPrint";
            public readonly string SetOrderFinlized = "SetOrderFinlized";
            public readonly string Delete = "Delete";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string OpenOrders = "OpenOrders";
            public const string Index = "Index";
            public const string NotFinalizedOrders = "NotFinalizedOrders";
            public const string FinalizedOrders = "FinalizedOrders";
            public const string OrderAdrdressPrint = "OrderAdrdressPrint";
            public const string SetOrderFinlized = "SetOrderFinlized";
            public const string Delete = "Delete";
        }


        static readonly ActionParamsClass_OrderAdrdressPrint s_params_OrderAdrdressPrint = new ActionParamsClass_OrderAdrdressPrint();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_OrderAdrdressPrint OrderAdrdressPrintParams { get { return s_params_OrderAdrdressPrint; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_OrderAdrdressPrint
        {
            public readonly string orderID = "orderID";
        }
        static readonly ActionParamsClass_SetOrderFinlized s_params_SetOrderFinlized = new ActionParamsClass_SetOrderFinlized();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetOrderFinlized SetOrderFinlizedParams { get { return s_params_SetOrderFinlized; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetOrderFinlized
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string FinalizedOrders = "FinalizedOrders";
                public readonly string Index = "Index";
                public readonly string NotFinalizedOrders = "NotFinalizedOrders";
                public readonly string OpenOrders = "OpenOrders";
                public readonly string OrderAdrdressPrint = "OrderAdrdressPrint";
            }
            public readonly string FinalizedOrders = "~/Areas/Admin/Views/Orders/FinalizedOrders.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Orders/Index.cshtml";
            public readonly string NotFinalizedOrders = "~/Areas/Admin/Views/Orders/NotFinalizedOrders.cshtml";
            public readonly string OpenOrders = "~/Areas/Admin/Views/Orders/OpenOrders.cshtml";
            public readonly string OrderAdrdressPrint = "~/Areas/Admin/Views/Orders/OrderAdrdressPrint.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_OrdersController : Web.Areas.Admin.Controllers.OrdersController
    {
        public T4MVC_OrdersController() : base(Dummy.Instance) { }

        [NonAction]
        partial void OpenOrdersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult OpenOrders()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OpenOrders);
            OpenOrdersOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NotFinalizedOrdersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult NotFinalizedOrders()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NotFinalizedOrders);
            NotFinalizedOrdersOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FinalizedOrdersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult FinalizedOrders()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FinalizedOrders);
            FinalizedOrdersOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void OrderAdrdressPrintOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int orderID);

        [NonAction]
        public override System.Web.Mvc.ActionResult OrderAdrdressPrint(int orderID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OrderAdrdressPrint);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderID", orderID);
            OrderAdrdressPrintOverride(callInfo, orderID);
            return callInfo;
        }

        [NonAction]
        partial void SetOrderFinlizedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult SetOrderFinlized(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetOrderFinlized);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            SetOrderFinlizedOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Delete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
