// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Web.Areas.Admin.Controllers
{
    public partial class DoorehController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected DoorehController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Index1()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Index1);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShowKelass()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowKelass);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddKelass()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddKelass);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteKelass()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteKelass);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShowProp()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowProp);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddDetiales()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddDetiales);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteDooreh()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteDooreh);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Gallery()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Gallery);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteGallery()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteGallery);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DoorehController Actions { get { return MVC.Admin.Dooreh; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Dooreh";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Dooreh";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Index1 = "Index1";
            public readonly string Create = "Create";
            public readonly string Edit = "Edit";
            public readonly string Delete = "Delete";
            public readonly string ShowKelass = "ShowKelass";
            public readonly string AddKelass = "AddKelass";
            public readonly string DeleteKelass = "DeleteKelass";
            public readonly string ShowProp = "ShowProp";
            public readonly string AddDetiales = "AddDetiales";
            public readonly string DeleteDooreh = "DeleteDooreh";
            public readonly string Gallery = "Gallery";
            public readonly string DeleteGallery = "DeleteGallery";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Index1 = "Index1";
            public const string Create = "Create";
            public const string Edit = "Edit";
            public const string Delete = "Delete";
            public const string ShowKelass = "ShowKelass";
            public const string AddKelass = "AddKelass";
            public const string DeleteKelass = "DeleteKelass";
            public const string ShowProp = "ShowProp";
            public const string AddDetiales = "AddDetiales";
            public const string DeleteDooreh = "DeleteDooreh";
            public const string Gallery = "Gallery";
            public const string DeleteGallery = "DeleteGallery";
        }


        static readonly ActionParamsClass_Index1 s_params_Index1 = new ActionParamsClass_Index1();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index1 Index1Params { get { return s_params_Index1; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index1
        {
            public readonly string request = "request";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string doorehVM = "doorehVM";
            public readonly string ImgDooreh = "ImgDooreh";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string id = "id";
            public readonly string doorehVM = "doorehVM";
            public readonly string ImgDooreh = "ImgDooreh";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ShowKelass s_params_ShowKelass = new ActionParamsClass_ShowKelass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowKelass ShowKelassParams { get { return s_params_ShowKelass; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowKelass
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddKelass s_params_AddKelass = new ActionParamsClass_AddKelass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddKelass AddKelassParams { get { return s_params_AddKelass; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddKelass
        {
            public readonly string doorehId = "doorehId";
            public readonly string doorehVM = "doorehVM";
        }
        static readonly ActionParamsClass_DeleteKelass s_params_DeleteKelass = new ActionParamsClass_DeleteKelass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteKelass DeleteKelassParams { get { return s_params_DeleteKelass; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteKelass
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ShowProp s_params_ShowProp = new ActionParamsClass_ShowProp();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowProp ShowPropParams { get { return s_params_ShowProp; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowProp
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddDetiales s_params_AddDetiales = new ActionParamsClass_AddDetiales();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddDetiales AddDetialesParams { get { return s_params_AddDetiales; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddDetiales
        {
            public readonly string doorehId = "doorehId";
            public readonly string doorehVM = "doorehVM";
        }
        static readonly ActionParamsClass_DeleteDooreh s_params_DeleteDooreh = new ActionParamsClass_DeleteDooreh();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteDooreh DeleteDoorehParams { get { return s_params_DeleteDooreh; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteDooreh
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Gallery s_params_Gallery = new ActionParamsClass_Gallery();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Gallery GalleryParams { get { return s_params_Gallery; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Gallery
        {
            public readonly string id = "id";
            public readonly string galleries = "galleries";
            public readonly string imgUp = "imgUp";
        }
        static readonly ActionParamsClass_DeleteGallery s_params_DeleteGallery = new ActionParamsClass_DeleteGallery();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteGallery DeleteGalleryParams { get { return s_params_DeleteGallery; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteGallery
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AddDetiales = "AddDetiales";
                public readonly string AddKelass = "AddKelass";
                public readonly string Create = "Create";
                public readonly string Edit = "Edit";
                public readonly string Gallery = "Gallery";
                public readonly string Index = "Index";
                public readonly string ShowKelass = "ShowKelass";
                public readonly string ShowProp = "ShowProp";
            }
            public readonly string AddDetiales = "~/Areas/Admin/Views/Dooreh/AddDetiales.cshtml";
            public readonly string AddKelass = "~/Areas/Admin/Views/Dooreh/AddKelass.cshtml";
            public readonly string Create = "~/Areas/Admin/Views/Dooreh/Create.cshtml";
            public readonly string Edit = "~/Areas/Admin/Views/Dooreh/Edit.cshtml";
            public readonly string Gallery = "~/Areas/Admin/Views/Dooreh/Gallery.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Dooreh/Index.cshtml";
            public readonly string ShowKelass = "~/Areas/Admin/Views/Dooreh/ShowKelass.cshtml";
            public readonly string ShowProp = "~/Areas/Admin/Views/Dooreh/ShowProp.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_DoorehController : Web.Areas.Admin.Controllers.DoorehController
    {
        public T4MVC_DoorehController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Index1Override(T4MVC_System_Web_Mvc_JsonResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, int? id);

        [NonAction]
        public override System.Web.Mvc.JsonResult Index1(Kendo.Mvc.UI.DataSourceRequest request, int? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Index1);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            Index1Override(callInfo, request, id);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            CreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ServiceLayer.Models.DoorehVM doorehVM, System.Web.HttpPostedFileBase ImgDooreh);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create(ServiceLayer.Models.DoorehVM doorehVM, System.Web.HttpPostedFileBase ImgDooreh)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "doorehVM", doorehVM);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ImgDooreh", ImgDooreh);
            CreateOverride(callInfo, doorehVM, ImgDooreh);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ServiceLayer.Models.DoorehVM doorehVM, System.Web.HttpPostedFileBase ImgDooreh);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(ServiceLayer.Models.DoorehVM doorehVM, System.Web.HttpPostedFileBase ImgDooreh)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "doorehVM", doorehVM);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ImgDooreh", ImgDooreh);
            EditOverride(callInfo, doorehVM, ImgDooreh);
            return callInfo;
        }

        [NonAction]
        partial void DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Delete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ShowKelassOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowKelass(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowKelass);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ShowKelassOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddKelassOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int doorehId);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddKelass(int doorehId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddKelass);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "doorehId", doorehId);
            AddKelassOverride(callInfo, doorehId);
            return callInfo;
        }

        [NonAction]
        partial void AddKelassOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ServiceLayer.Models.DoorehVM doorehVM);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddKelass(ServiceLayer.Models.DoorehVM doorehVM)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddKelass);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "doorehVM", doorehVM);
            AddKelassOverride(callInfo, doorehVM);
            return callInfo;
        }

        [NonAction]
        partial void DeleteKelassOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteKelass(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteKelass);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteKelassOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ShowPropOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowProp(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowProp);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ShowPropOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddDetialesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int doorehId);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddDetiales(int doorehId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddDetiales);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "doorehId", doorehId);
            AddDetialesOverride(callInfo, doorehId);
            return callInfo;
        }

        [NonAction]
        partial void AddDetialesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ServiceLayer.Models.DoorehVM doorehVM);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddDetiales(ServiceLayer.Models.DoorehVM doorehVM)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddDetiales);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "doorehVM", doorehVM);
            AddDetialesOverride(callInfo, doorehVM);
            return callInfo;
        }

        [NonAction]
        partial void DeleteDoorehOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteDooreh(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteDooreh);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteDoorehOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void GalleryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Gallery(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Gallery);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GalleryOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void GalleryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, DomainClass.Models.Image galleries, System.Web.HttpPostedFileBase imgUp);

        [NonAction]
        public override System.Web.Mvc.ActionResult Gallery(DomainClass.Models.Image galleries, System.Web.HttpPostedFileBase imgUp)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Gallery);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "galleries", galleries);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "imgUp", imgUp);
            GalleryOverride(callInfo, galleries, imgUp);
            return callInfo;
        }

        [NonAction]
        partial void DeleteGalleryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteGallery(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteGallery);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteGalleryOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
