// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Web.Areas.Admin.Controllers
{
    public partial class PackagesController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PackagesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult HierarchyBinding_Packages()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HierarchyBinding_Packages);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult HierarchyBinding_ChildPackages()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HierarchyBinding_ChildPackages);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShowProp()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowProp);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddDetiales()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddDetiales);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteProduct()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteProduct);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Gallery()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Gallery);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteGallery()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteGallery);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PackagesController Actions { get { return MVC.Admin.Packages; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Packages";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Packages";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string ListPackages = "ListPackages";
            public readonly string Hierarchy = "Hierarchy";
            public readonly string PackageTree = "PackageTree";
            public readonly string HierarchyBinding_Packages = "HierarchyBinding_Packages";
            public readonly string HierarchyBinding_ChildPackages = "HierarchyBinding_ChildPackages";
            public readonly string Create = "Create";
            public readonly string Edit = "Edit";
            public readonly string Delete = "Delete";
            public readonly string ShowProp = "ShowProp";
            public readonly string AddDetiales = "AddDetiales";
            public readonly string DeleteProduct = "DeleteProduct";
            public readonly string Gallery = "Gallery";
            public readonly string DeleteGallery = "DeleteGallery";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string ListPackages = "ListPackages";
            public const string Hierarchy = "Hierarchy";
            public const string PackageTree = "PackageTree";
            public const string HierarchyBinding_Packages = "HierarchyBinding_Packages";
            public const string HierarchyBinding_ChildPackages = "HierarchyBinding_ChildPackages";
            public const string Create = "Create";
            public const string Edit = "Edit";
            public const string Delete = "Delete";
            public const string ShowProp = "ShowProp";
            public const string AddDetiales = "AddDetiales";
            public const string DeleteProduct = "DeleteProduct";
            public const string Gallery = "Gallery";
            public const string DeleteGallery = "DeleteGallery";
        }


        static readonly ActionParamsClass_HierarchyBinding_Packages s_params_HierarchyBinding_Packages = new ActionParamsClass_HierarchyBinding_Packages();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_HierarchyBinding_Packages HierarchyBinding_PackagesParams { get { return s_params_HierarchyBinding_Packages; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_HierarchyBinding_Packages
        {
            public readonly string request = "request";
        }
        static readonly ActionParamsClass_HierarchyBinding_ChildPackages s_params_HierarchyBinding_ChildPackages = new ActionParamsClass_HierarchyBinding_ChildPackages();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_HierarchyBinding_ChildPackages HierarchyBinding_ChildPackagesParams { get { return s_params_HierarchyBinding_ChildPackages; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_HierarchyBinding_ChildPackages
        {
            public readonly string parentId = "parentId";
            public readonly string request = "request";
        }
        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string packageVM = "packageVM";
            public readonly string ImgPackage = "ImgPackage";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string id = "id";
            public readonly string packageVM = "packageVM";
            public readonly string ImgPackage = "ImgPackage";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ShowProp s_params_ShowProp = new ActionParamsClass_ShowProp();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowProp ShowPropParams { get { return s_params_ShowProp; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowProp
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddDetiales s_params_AddDetiales = new ActionParamsClass_AddDetiales();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddDetiales AddDetialesParams { get { return s_params_AddDetiales; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddDetiales
        {
            public readonly string packageId = "packageId";
            public readonly string vmPackageProduct = "vmPackageProduct";
        }
        static readonly ActionParamsClass_DeleteProduct s_params_DeleteProduct = new ActionParamsClass_DeleteProduct();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteProduct DeleteProductParams { get { return s_params_DeleteProduct; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteProduct
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Gallery s_params_Gallery = new ActionParamsClass_Gallery();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Gallery GalleryParams { get { return s_params_Gallery; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Gallery
        {
            public readonly string id = "id";
            public readonly string galleries = "galleries";
            public readonly string imgUp = "imgUp";
        }
        static readonly ActionParamsClass_DeleteGallery s_params_DeleteGallery = new ActionParamsClass_DeleteGallery();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteGallery DeleteGalleryParams { get { return s_params_DeleteGallery; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteGallery
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AddDetiales = "AddDetiales";
                public readonly string Create = "Create";
                public readonly string Create1 = "Create1";
                public readonly string Edit = "Edit";
                public readonly string Gallery = "Gallery";
                public readonly string Hierarchy = "Hierarchy";
                public readonly string Index = "Index";
                public readonly string Index1 = "Index1";
                public readonly string ListPackages = "ListPackages";
                public readonly string PackageTree = "PackageTree";
                public readonly string ShowPicture = "ShowPicture";
                public readonly string ShowProp = "ShowProp";
            }
            public readonly string AddDetiales = "~/Areas/Admin/Views/Packages/AddDetiales.cshtml";
            public readonly string Create = "~/Areas/Admin/Views/Packages/Create.cshtml";
            public readonly string Create1 = "~/Areas/Admin/Views/Packages/Create1.cshtml";
            public readonly string Edit = "~/Areas/Admin/Views/Packages/Edit.cshtml";
            public readonly string Gallery = "~/Areas/Admin/Views/Packages/Gallery.cshtml";
            public readonly string Hierarchy = "~/Areas/Admin/Views/Packages/Hierarchy.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Packages/Index.cshtml";
            public readonly string Index1 = "~/Areas/Admin/Views/Packages/Index1.cshtml";
            public readonly string ListPackages = "~/Areas/Admin/Views/Packages/ListPackages.cshtml";
            public readonly string PackageTree = "~/Areas/Admin/Views/Packages/PackageTree.cshtml";
            public readonly string ShowPicture = "~/Areas/Admin/Views/Packages/ShowPicture.cshtml";
            public readonly string ShowProp = "~/Areas/Admin/Views/Packages/ShowProp.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PackagesController : Web.Areas.Admin.Controllers.PackagesController
    {
        public T4MVC_PackagesController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ListPackagesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListPackages()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListPackages);
            ListPackagesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void HierarchyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hierarchy()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hierarchy);
            HierarchyOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PackageTreeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PackageTree()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PackageTree);
            PackageTreeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void HierarchyBinding_PackagesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request);

        [NonAction]
        public override System.Web.Mvc.ActionResult HierarchyBinding_Packages(Kendo.Mvc.UI.DataSourceRequest request)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HierarchyBinding_Packages);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            HierarchyBinding_PackagesOverride(callInfo, request);
            return callInfo;
        }

        [NonAction]
        partial void HierarchyBinding_ChildPackagesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int parentId, Kendo.Mvc.UI.DataSourceRequest request);

        [NonAction]
        public override System.Web.Mvc.ActionResult HierarchyBinding_ChildPackages(int parentId, Kendo.Mvc.UI.DataSourceRequest request)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HierarchyBinding_ChildPackages);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentId", parentId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            HierarchyBinding_ChildPackagesOverride(callInfo, parentId, request);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            CreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ServiceLayer.Models.PackageVM packageVM, System.Web.HttpPostedFileBase ImgPackage);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create(ServiceLayer.Models.PackageVM packageVM, System.Web.HttpPostedFileBase ImgPackage)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "packageVM", packageVM);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ImgPackage", ImgPackage);
            CreateOverride(callInfo, packageVM, ImgPackage);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ServiceLayer.Models.PackageVM packageVM, System.Web.HttpPostedFileBase ImgPackage);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(ServiceLayer.Models.PackageVM packageVM, System.Web.HttpPostedFileBase ImgPackage)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "packageVM", packageVM);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ImgPackage", ImgPackage);
            EditOverride(callInfo, packageVM, ImgPackage);
            return callInfo;
        }

        [NonAction]
        partial void DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Delete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ShowPropOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowProp(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowProp);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ShowPropOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddDetialesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int packageId);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddDetiales(int packageId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddDetiales);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "packageId", packageId);
            AddDetialesOverride(callInfo, packageId);
            return callInfo;
        }

        [NonAction]
        partial void AddDetialesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ServiceLayer.Models.PackageProductVM vmPackageProduct);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddDetiales(ServiceLayer.Models.PackageProductVM vmPackageProduct)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddDetiales);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vmPackageProduct", vmPackageProduct);
            AddDetialesOverride(callInfo, vmPackageProduct);
            return callInfo;
        }

        [NonAction]
        partial void DeleteProductOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteProduct(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteProduct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteProductOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void GalleryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Gallery(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Gallery);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GalleryOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void GalleryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, DomainClass.Models.Image galleries, System.Web.HttpPostedFileBase imgUp);

        [NonAction]
        public override System.Web.Mvc.ActionResult Gallery(DomainClass.Models.Image galleries, System.Web.HttpPostedFileBase imgUp)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Gallery);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "galleries", galleries);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "imgUp", imgUp);
            GalleryOverride(callInfo, galleries, imgUp);
            return callInfo;
        }

        [NonAction]
        partial void DeleteGalleryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteGallery(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteGallery);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteGalleryOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
