// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Web.Controllers
{
    public partial class NewsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected NewsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult NewsDetail()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewsDetail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult InsertComment()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.InsertComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult NewsLike()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.NewsLike);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult NewsDisLike()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.NewsDisLike);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public NewsController Actions { get { return MVC.News; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "News";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "News";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string NewsDetail = "NewsDetail";
            public readonly string InsertComment = "InsertComment";
            public readonly string FillComments = "FillComments";
            public readonly string NewsLike = "NewsLike";
            public readonly string NewsDisLike = "NewsDisLike";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string NewsDetail = "NewsDetail";
            public const string InsertComment = "InsertComment";
            public const string FillComments = "FillComments";
            public const string NewsLike = "NewsLike";
            public const string NewsDisLike = "NewsDisLike";
        }


        static readonly ActionParamsClass_NewsDetail s_params_NewsDetail = new ActionParamsClass_NewsDetail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NewsDetail NewsDetailParams { get { return s_params_NewsDetail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NewsDetail
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_InsertComment s_params_InsertComment = new ActionParamsClass_InsertComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InsertComment InsertCommentParams { get { return s_params_InsertComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InsertComment
        {
            public readonly string t = "t";
        }
        static readonly ActionParamsClass_FillComments s_params_FillComments = new ActionParamsClass_FillComments();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FillComments FillCommentsParams { get { return s_params_FillComments; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FillComments
        {
            public readonly string newsId = "newsId";
        }
        static readonly ActionParamsClass_NewsLike s_params_NewsLike = new ActionParamsClass_NewsLike();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NewsLike NewsLikeParams { get { return s_params_NewsLike; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NewsLike
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_NewsDisLike s_params_NewsDisLike = new ActionParamsClass_NewsDisLike();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NewsDisLike NewsDisLikeParams { get { return s_params_NewsDisLike; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NewsDisLike
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _CommentPartial = "_CommentPartial";
                public readonly string Index = "Index";
                public readonly string NewsDetail = "NewsDetail";
                public readonly string NewsDetail2 = "NewsDetail2";
            }
            public readonly string _CommentPartial = "~/Views/News/_CommentPartial.cshtml";
            public readonly string Index = "~/Views/News/Index.cshtml";
            public readonly string NewsDetail = "~/Views/News/NewsDetail.cshtml";
            public readonly string NewsDetail2 = "~/Views/News/NewsDetail2.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_NewsController : Web.Controllers.NewsController
    {
        public T4MVC_NewsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NewsDetailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult NewsDetail(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewsDetail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            NewsDetailOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void InsertCommentOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, DomainClass.Models.Comments t);

        [NonAction]
        public override System.Web.Mvc.JsonResult InsertComment(DomainClass.Models.Comments t)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.InsertComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "t", t);
            InsertCommentOverride(callInfo, t);
            return callInfo;
        }

        [NonAction]
        partial void FillCommentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int newsId);

        [NonAction]
        public override System.Web.Mvc.ActionResult FillComments(int newsId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FillComments);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "newsId", newsId);
            FillCommentsOverride(callInfo, newsId);
            return callInfo;
        }

        [NonAction]
        partial void NewsLikeOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult NewsLike(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.NewsLike);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            NewsLikeOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void NewsDisLikeOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult NewsDisLike(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.NewsDisLike);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            NewsDisLikeOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
